# Basic
title: Saint Emperor
subtitle: 北湖傍晚
welcome_message: <a href="https://github.com/paracortex" target="_blank">View One Web</a>
description: 以刚克刚 极理悍行.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/paracortex'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: paracortex
    # duoshuo:

# Social
social:
  #  weibo: onevcat
    github: paracortex
    twitter: Paracortex
  #  gplus: 107108267983477358170
  #  mail: saintseiya@protonmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
